//SUCCESS
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS';

//ERROR
export const ERROR_GET_ALL_USER = 'ERROR_GET_ALL_USER';
export const ERROR_USER_ALREADY_EXIST = 'ERROR_USER_ALREADY_EXIST';
export const ERROR_USER_NOT_FOUND = 'ERROR_USER_ALREADY_EXIST';
export const ERROR_CREATE_USER = 'ERROR_CREATE_USE';
export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';
export const ERROR_PASSWORD_USER_INCORRECT = 'ERROR_PASSWORD_USER_INCORRECT';
export const ERROR_PASSWORD_USER_UNSAFE = 'ERROR_PASSWORD_USER_UNSAFE';
export const ERROR_PASSWORD_USER_NOT_MATCH = 'ERROR_PASSWORD_USER_NOT_MATCH';
export const ERROR_CHANGE_PASSWORD_USER = 'ERROR_CHANGE_PASSWORD_USER';

export const ERROR_IS_NOT_DATE_TIME = 'ERROR_IS_NOT_DATE_TIME';
export const ERROR_IS_NOT_PHONE_NUMBER = 'ERROR_IS_NOT_PHONE_NUMBER';
