//SUCCESS
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const LOGOUT_SUCCESS = 'REFRESH_TOKEN_SUCCESS';

//ERROR
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const ERROR_REFRESH_TOKEN = 'ERROR_REFRESH_TOKEN';
export const ERROR_ACCESS_DENIED = 'ERROR_ACCESS_DENIED';
export const ERROR_LOGOUT = 'ERROR_LOGOUT';
